/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testderivative;

import java.awt.Color;

/**
 *
 * @author kenicia
 */
public class DerivativeGUI extends javax.swing.JFrame {

    /**
     * Creates new form DerivativeGUI
     */
    public DerivativeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        titleLabel_2 = new javax.swing.JLabel();
        lLabelPanel = new javax.swing.JPanel();
        sidePanel_2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dLabelPanel = new javax.swing.JPanel();
        sidePanel_1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bLabelPanel = new javax.swing.JPanel();
        sidePanel_3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sLabelPanel = new javax.swing.JPanel();
        sidePanel_4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        calcLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        derivativePanel = new javax.swing.JPanel();
        dInputTextField = new javax.swing.JTextField();
        dAnswerLabel = new javax.swing.JLabel();
        dTitleLabel = new javax.swing.JLabel();
        sSolveButton = new javax.swing.JLabel();
        loanPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        bmrPanel = new javax.swing.JPanel();
        bTitleLabel = new javax.swing.JLabel();
        savingsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator Galore");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("mainFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Big Caslon", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Calculator ");
        jPanel2.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        titleLabel_2.setFont(new java.awt.Font("Big Caslon", 1, 24)); // NOI18N
        titleLabel_2.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel_2.setText("Galore");
        jPanel2.add(titleLabel_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        lLabelPanel.setOpaque(false);
        lLabelPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lLabelPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lLabelPanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lLabelPanelMouseEntered(evt);
            }
        });
        lLabelPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel_2.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel_2.setOpaque(false);

        javax.swing.GroupLayout sidePanel_2Layout = new javax.swing.GroupLayout(sidePanel_2);
        sidePanel_2.setLayout(sidePanel_2Layout);
        sidePanel_2Layout.setHorizontalGroup(
            sidePanel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        sidePanel_2Layout.setVerticalGroup(
            sidePanel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        lLabelPanel.add(sidePanel_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel1.setFont(new java.awt.Font("Big Caslon", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 234, 244));
        jLabel1.setText("Loan Payoff Calculator");
        lLabelPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(lLabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 180, 50));

        dLabelPanel.setBackground(new java.awt.Color(204, 152, 228));
        dLabelPanel.setOpaque(false);
        dLabelPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dLabelPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dLabelPanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dLabelPanelMouseEntered(evt);
            }
        });
        dLabelPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel_1.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel_1.setOpaque(false);

        javax.swing.GroupLayout sidePanel_1Layout = new javax.swing.GroupLayout(sidePanel_1);
        sidePanel_1.setLayout(sidePanel_1Layout);
        sidePanel_1Layout.setHorizontalGroup(
            sidePanel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        sidePanel_1Layout.setVerticalGroup(
            sidePanel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        dLabelPanel.add(sidePanel_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel2.setFont(new java.awt.Font("Big Caslon", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 234, 244));
        jLabel2.setText("Derivative Calculator");
        dLabelPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(dLabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 180, 50));

        bLabelPanel.setOpaque(false);
        bLabelPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLabelPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bLabelPanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bLabelPanelMouseEntered(evt);
            }
        });
        bLabelPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel_3.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel_3.setOpaque(false);

        javax.swing.GroupLayout sidePanel_3Layout = new javax.swing.GroupLayout(sidePanel_3);
        sidePanel_3.setLayout(sidePanel_3Layout);
        sidePanel_3Layout.setHorizontalGroup(
            sidePanel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        sidePanel_3Layout.setVerticalGroup(
            sidePanel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        bLabelPanel.add(sidePanel_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel3.setFont(new java.awt.Font("Big Caslon", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(243, 234, 244));
        jLabel3.setText("BMR Calculator");
        bLabelPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(bLabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 180, 50));

        sLabelPanel.setOpaque(false);
        sLabelPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sLabelPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sLabelPanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sLabelPanelMouseEntered(evt);
            }
        });
        sLabelPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel_4.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel_4.setOpaque(false);

        javax.swing.GroupLayout sidePanel_4Layout = new javax.swing.GroupLayout(sidePanel_4);
        sidePanel_4.setLayout(sidePanel_4Layout);
        sidePanel_4Layout.setHorizontalGroup(
            sidePanel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        sidePanel_4Layout.setVerticalGroup(
            sidePanel_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        sLabelPanel.add(sidePanel_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel4.setFont(new java.awt.Font("Big Caslon", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(243, 234, 244));
        jLabel4.setText("Savings Calculator");
        sLabelPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(sLabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 180, 50));

        calcLabel.setBackground(new java.awt.Color(240, 233, 155));
        calcLabel.setFont(new java.awt.Font("Big Caslon", 0, 14)); // NOI18N
        calcLabel.setForeground(new java.awt.Color(255, 255, 153));
        calcLabel.setText("CALCULATORS");
        calcLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcLabelMouseClicked(evt);
            }
        });
        jPanel2.add(calcLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 450));

        jPanel3.setBackground(new java.awt.Color(226, 208, 231));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomePanel.setBackground(new java.awt.Color(226, 208, 231));
        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Big Caslon", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 204));
        jLabel7.setText("Welcome to");
        welcomePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Big Caslon", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 204));
        jLabel9.setText("Calculator Galore");
        welcomePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jPanel3.add(welcomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 450));

        derivativePanel.setBackground(new java.awt.Color(225, 225, 111));
        derivativePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dInputTextField.setFont(new java.awt.Font("Big Caslon", 0, 24)); // NOI18N
        dInputTextField.setText("polynomial goes here");
        dInputTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dInputTextFieldMouseClicked(evt);
            }
        });
        derivativePanel.add(dInputTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 299, -1));

        dAnswerLabel.setFont(new java.awt.Font("Big Caslon", 0, 36)); // NOI18N
        dAnswerLabel.setForeground(new java.awt.Color(102, 0, 102));
        dAnswerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dAnswerLabel.setText("Answer goes here");
        derivativePanel.add(dAnswerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 450, -1));

        dTitleLabel.setFont(new java.awt.Font("Big Caslon", 0, 40)); // NOI18N
        dTitleLabel.setForeground(new java.awt.Color(102, 0, 102));
        dTitleLabel.setText("Derivative Calculator");
        derivativePanel.add(dTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        sSolveButton.setBackground(new java.awt.Color(204, 0, 102));
        sSolveButton.setFont(new java.awt.Font("Big Caslon", 0, 18)); // NOI18N
        sSolveButton.setForeground(new java.awt.Color(255, 255, 255));
        sSolveButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sSolveButton.setText("Solve");
        sSolveButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        sSolveButton.setOpaque(true);
        derivativePanel.add(sSolveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 90, 40));

        jPanel3.add(derivativePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 450));
        derivativePanel.setVisible(false);
        derivativePanel.getAccessibleContext().setAccessibleParent(mainPanel);

        loanPanel.setBackground(new java.awt.Color(225, 225, 111));
        loanPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        loanPanel.setVisible(false);

        jLabel6.setFont(new java.awt.Font("Big Caslon", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Loan Payoff Calculator");
        loanPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jPanel3.add(loanPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 450));

        bmrPanel.setBackground(new java.awt.Color(225, 225, 111));
        bmrPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bTitleLabel.setFont(new java.awt.Font("Big Caslon", 0, 40)); // NOI18N
        bTitleLabel.setForeground(new java.awt.Color(102, 0, 102));
        bTitleLabel.setText("BMR Calculator");
        bmrPanel.add(bTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jPanel3.add(bmrPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 450));

        savingsPanel.setBackground(new java.awt.Color(225, 225, 111));
        savingsPanel.setToolTipText("");
        savingsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Big Caslon", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Savings Interest Calculator");
        savingsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jPanel3.add(savingsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 450));

        mainPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 520, 450));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dLabelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dLabelPanelMouseEntered
        // TODO add your handling code here:
        dLabelPanel.setBackground(new java.awt.Color(200,152,228));
        dLabelPanel.setOpaque(true);
        sidePanel_1.setBackground(Color.white);
        sidePanel_1.setOpaque(true);
        
    }//GEN-LAST:event_dLabelPanelMouseEntered

    private void dLabelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dLabelPanelMouseExited
        // TODO add your handling code here:
        dLabelPanel.setBackground(new java.awt.Color(140,99,148));
        dLabelPanel.setOpaque(false);
        sidePanel_1.setBackground(new java.awt.Color(140,99,148));
        sidePanel_1.setOpaque(false);
    }//GEN-LAST:event_dLabelPanelMouseExited

    private void lLabelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lLabelPanelMouseEntered
        // TODO add your handling code here:
        lLabelPanel.setBackground(new java.awt.Color(200,152,228));
        lLabelPanel.setOpaque(true);
        sidePanel_2.setBackground(Color.white);
        sidePanel_2.setOpaque(true);
    }//GEN-LAST:event_lLabelPanelMouseEntered

    private void lLabelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lLabelPanelMouseExited
        // TODO add your handling code here:
        lLabelPanel.setBackground(new java.awt.Color(140,99,148));
        lLabelPanel.setOpaque(false);
        sidePanel_2.setBackground(new java.awt.Color(140,99,148));
        sidePanel_2.setOpaque(false);
    }//GEN-LAST:event_lLabelPanelMouseExited

    private void bLabelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLabelPanelMouseEntered
        // TODO add your handling code here:
        bLabelPanel.setBackground(new java.awt.Color(200,152,228));
        bLabelPanel.setOpaque(true);
        sidePanel_3.setBackground(Color.white);
        sidePanel_3.setOpaque(true);
    }//GEN-LAST:event_bLabelPanelMouseEntered

    private void bLabelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLabelPanelMouseExited
        // TODO add your handling code here:
        bLabelPanel.setBackground(new java.awt.Color(140,99,148));
        bLabelPanel.setOpaque(false);
        sidePanel_3.setBackground(new java.awt.Color(140,99,148));
        sidePanel_3.setOpaque(false);
    }//GEN-LAST:event_bLabelPanelMouseExited

    private void sLabelPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sLabelPanelMouseEntered
        // TODO add your handling code here:
        sLabelPanel.setBackground(new java.awt.Color(200,152,228));
        sLabelPanel.setOpaque(true);
        sidePanel_4.setBackground(Color.white);
        sidePanel_4.setOpaque(true);
    }//GEN-LAST:event_sLabelPanelMouseEntered

    private void sLabelPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sLabelPanelMouseExited
        // TODO add your handling code here:
        sLabelPanel.setBackground(new java.awt.Color(140,99,148));
        sLabelPanel.setOpaque(false);
        sidePanel_4.setBackground(new java.awt.Color(140,99,148));
        sidePanel_4.setOpaque(false);
    }//GEN-LAST:event_sLabelPanelMouseExited

    private void dLabelPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dLabelPanelMouseClicked
        // TODO add your handling code here:
        derivativePanel.setVisible(true);
        welcomePanel.setVisible(false);
        loanPanel.setVisible(false);
        bmrPanel.setVisible(false);
        savingsPanel.setVisible(false);
    }//GEN-LAST:event_dLabelPanelMouseClicked

    private void calcLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcLabelMouseClicked
        // TODO add your handling code here:
        derivativePanel.setVisible(false);
        loanPanel.setVisible(false);
        bmrPanel.setVisible(false);
        welcomePanel.setVisible(true);
        savingsPanel.setVisible(false);
    }//GEN-LAST:event_calcLabelMouseClicked

    private void dInputTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dInputTextFieldMouseClicked
        // TODO add your handling code here:
        dInputTextField.setText("");
    }//GEN-LAST:event_dInputTextFieldMouseClicked

    private void lLabelPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lLabelPanelMouseClicked
        // TODO add your handling code here:
        derivativePanel.setVisible(false);
        welcomePanel.setVisible(false);
        bmrPanel.setVisible(false);
        loanPanel.setVisible(true);
        savingsPanel.setVisible(false);
    }//GEN-LAST:event_lLabelPanelMouseClicked

    private void bLabelPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLabelPanelMouseClicked
        // TODO add your handling code here:
        derivativePanel.setVisible(false);
        loanPanel.setVisible(false);
        welcomePanel.setVisible(false);
        bmrPanel.setVisible(true);
        savingsPanel.setVisible(false);
    }//GEN-LAST:event_bLabelPanelMouseClicked

    private void sLabelPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sLabelPanelMouseClicked
        // TODO add your handling code here:
        derivativePanel.setVisible(false);
        loanPanel.setVisible(false);
        welcomePanel.setVisible(false);
        bmrPanel.setVisible(false);
        savingsPanel.setVisible(true);
    }//GEN-LAST:event_sLabelPanelMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DerivativeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DerivativeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DerivativeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DerivativeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DerivativeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bLabelPanel;
    private javax.swing.JLabel bTitleLabel;
    private javax.swing.JPanel bmrPanel;
    private javax.swing.JLabel calcLabel;
    private javax.swing.JLabel dAnswerLabel;
    private javax.swing.JTextField dInputTextField;
    private javax.swing.JPanel dLabelPanel;
    private javax.swing.JLabel dTitleLabel;
    private javax.swing.JPanel derivativePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel lLabelPanel;
    private javax.swing.JPanel loanPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel sLabelPanel;
    private javax.swing.JLabel sSolveButton;
    private javax.swing.JPanel savingsPanel;
    private javax.swing.JPanel sidePanel_1;
    private javax.swing.JPanel sidePanel_2;
    private javax.swing.JPanel sidePanel_3;
    private javax.swing.JPanel sidePanel_4;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel_2;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
